(function () {
  "use strict";
  const KEY = "timeflow-private-account-v1";
  const AUDIT_KEY = "timeflow-worktime-audit-v1";
  const TARGETS_KEY = "timeflow-monthly-targets-v1";
  const platform = () => window.TimeFlowPlatform;
  const read = () => { try { const value = JSON.parse(platform().storage.getItem(KEY) || "[]"); return Array.isArray(value) ? value : []; } catch (_error) { return []; } };
  const write = (entries) => platform().storage.setItem(KEY, JSON.stringify(entries));
  const settings = () => { try { return JSON.parse(platform().storage.getItem("timeflow-settings-v1") || "{}"); } catch (_error) { return {}; } };
  const readObject = (key) => { try { const value = JSON.parse(platform().storage.getItem(key) || "{}"); return value && typeof value === "object" && !Array.isArray(value) ? value : {}; } catch (_error) { return {}; } };
  const locale = () => window.TimeFlowLocalization?.locale?.() || "de-DE";
  const audit = (action, entry, before = null) => { const log = readObject(AUDIT_KEY); const events = Array.isArray(log.events) ? log.events : []; events.push({ id: `audit-${Date.now()}`, at: new Date().toISOString(), action, entryId: entry.id, date: entry.date, before, after: entry }); platform().storage.setItem(AUDIT_KEY, JSON.stringify({ events: events.slice(-500) })); };
  const format = (minutes, signed = false) => { const sign = minutes < 0 ? "−" : signed && minutes > 0 ? "+" : ""; const value = Math.abs(Math.round(minutes)); return `${sign}${Math.floor(value / 60)} h ${value % 60} min`; };
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  function downloadCsv(entries) {
    const rows = [["Datum", "Art", "Notiz", "Arbeitszeit Minuten", "Soll Minuten", "Korrektur Minuten"], ...entries.map((entry) => [entry.date, entry.source === "stamp" ? "Stempelung" : "Manuell", entry.note || "", entry.minutes || 0, entry.target || 0, entry.adjustment || 0])];
    const csv = rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(";")).join("\r\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); link.download = `timeflow-arbeitszeitkonto-${new Date().toLocaleDateString("sv-SE")}.csv`; link.click(); URL.revokeObjectURL(link.href);
  }
  function printPdf(entries) {
    const popup = window.open("", "_blank", "noopener,noreferrer"); if (!popup) return;
    const rows = entries.map((entry) => `<tr><td>${escapeHtml(entry.date)}</td><td>${entry.source === "stamp" ? "Stempelung" : "Korrektur"}</td><td>${escapeHtml(entry.note || "")}</td><td>${entry.source === "stamp" ? format(entry.minutes) : format(entry.adjustment, true)}</td></tr>`).join("");
    popup.document.write(`<!doctype html><html lang="${document.documentElement.lang}"><head><meta charset="utf-8"><title>TimeFlow Arbeitszeitkonto</title><style>body{font:14px Arial;padding:32px;color:#10243b}h1{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:9px;border-bottom:1px solid #ccd6e0;text-align:left}</style></head><body><h1>TimeFlow Arbeitszeitkonto</h1><p>Export vom ${new Date().toLocaleString(locale())}</p><table><thead><tr><th>Datum</th><th>Art</th><th>Notiz</th><th>Wert</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`); popup.document.close();
  }
  function captureCompletedWorkday() {
    let workday; try { workday = JSON.parse(platform().storage.getItem("timeflow-workday-v2") || "null"); } catch (_error) { return; }
    if (!workday?.workStart || !workday.workEnd || workday.isWorking) return;
    const entries = read(); const id = `stamp-${workday.workEnd}`; if (entries.some((entry) => entry.id === id)) return;
    const gross = Math.max(0, Math.floor((new Date(workday.workEnd) - new Date(workday.workStart)) / 60000)); const config = settings(); const pause = workday.hasManualPause ? Math.floor(Number(workday.pauseAccumulatedMs || 0) / 60000) : gross >= Number(config.autoBreakAfterMinutes || 360) ? Number(config.autoBreakMinutes || 30) : 0; const net = Math.max(0, gross - pause); const target = Number(config.dailyTargetMinutes || 480);
    entries.push({ id, date: new Date(workday.workStart).toLocaleDateString("sv-SE"), minutes: net, target, adjustment: 0, note: "Stempelung", source: "stamp" }); write(entries); document.dispatchEvent(new CustomEvent("timeflow:private-account-updated"));
  }
  function monthlyValues(month = new Date().toLocaleDateString("sv-SE").slice(0, 7)) {
    captureCompletedWorkday();
    const monthEntries = read().filter((entry) => String(entry.date || "").startsWith(month));
    let stamped = monthEntries.filter((entry) => entry.source === "stamp").reduce((sum, entry) => sum + Number(entry.minutes || 0), 0);
    const manual = monthEntries.filter((entry) => entry.source === "manual").reduce((sum, entry) => sum + Number(entry.adjustment || 0), 0);
    const workday = readObject("timeflow-workday-v2");
    if (workday?.isWorking && String(workday.workStart || "").slice(0, 7) === month) {
      const gross = Math.max(0, Math.floor((Date.now() - new Date(workday.workStart).getTime()) / 60000));
      const config = settings();
      const runningPause = workday.isPaused && workday.pauseStartedAt ? Math.max(0, Date.now() - new Date(workday.pauseStartedAt).getTime()) : 0;
      const pause = workday.hasManualPause ? Math.floor((Number(workday.pauseAccumulatedMs || 0) + runningPause) / 60000) : gross >= Number(config.autoBreakAfterMinutes || 360) ? Number(config.autoBreakMinutes || 30) : 0;
      stamped += Math.max(0, gross - pause);
    }
    const targets = readObject(TARGETS_KEY);
    const target = Math.round(Number(targets[month] ?? settings().monthlyTargetHours ?? 160) * 60);
    return { stamped, manual, target, balance: stamped + manual - target, entries: monthEntries };
  }
  function renderHomeMonth() {
    const currentMonth = new Date().toLocaleDateString("sv-SE").slice(0, 7);
    const values = monthlyValues(currentMonth);
    const hours = document.getElementById("todayHours");
    const overtime = document.getElementById("todayOvertime");
    if (hours) hours.textContent = format(values.stamped + values.manual);
    if (overtime) overtime.textContent = format(values.balance, true);
    return values;
  }
  function install() {
    document.body.insertAdjacentHTML("beforeend", `<dialog class="private-account-dialog" id="privateAccountDialog"><header><div><small>PRIVAT · ARBEITSZEITKONTO</small><h2>Mein Arbeitszeitkonto</h2><p>Stempelungen werden automatisch übernommen. Anfangsstände und Korrekturen kannst du manuell ergänzen.</p></div><button type="button" data-close-private-account aria-label="Schließen"><i class="fa-solid fa-xmark"></i></button></header><section class="private-account-summary"><span><small>ERFASSTE ARBEITSZEIT</small><strong data-account-stamped>0 h 0 min</strong></span><span><small>MANUELLE KORREKTUREN</small><strong data-account-manual>0 h 0 min</strong></span><span><small>AKTUELLER SALDO</small><strong data-account-balance>0 h 0 min</strong></span></section><form class="private-account-form"><label>Datum<input name="date" type="date" required></label><label>Art<select name="direction"><option value="1">Guthaben hinzufügen</option><option value="-1">Stunden abziehen</option></select></label><label>Stunden<input name="hours" type="number" min="0" max="9999" value="0" required></label><label>Minuten<input name="minutes" type="number" min="0" max="59" value="0" required></label><label>Notiz<input name="note" type="text" maxlength="80" placeholder="z. B. Anfangsstand oder Korrektur"></label><button type="submit"><i class="fa-solid fa-plus"></i> Im Arbeitszeitkonto speichern</button></form><section class="private-account-list" data-account-list></section></dialog>`);
    const dialog = document.getElementById("privateAccountDialog"); const form = dialog.querySelector("form"); form.elements.date.value = new Date().toLocaleDateString("sv-SE"); dialog.querySelector(".private-account-summary").insertAdjacentHTML("beforeend", `<span><small>MONATSSOLL</small><strong data-account-target>0 h 0 min</strong></span>`); dialog.querySelector(".private-account-summary").insertAdjacentHTML("afterend", `<label class="private-account-period"><i class="fa-regular fa-calendar"></i><span>Monatsarchiv</span><input type="month" data-account-month-picker aria-label="Monat auswählen"></label><div class="private-account-export"><button type="button" data-account-csv><i class="fa-solid fa-file-csv"></i> CSV exportieren</button><button type="button" data-account-pdf><i class="fa-solid fa-file-pdf"></i> PDF speichern</button><button type="button" data-account-audit><i class="fa-solid fa-clock-rotate-left"></i> Änderungsverlauf</button></div><section class="private-account-audit" data-account-audit-list hidden></section>`); const monthPicker = dialog.querySelector("[data-account-month-picker]"); monthPicker.value = new Date().toLocaleDateString("sv-SE").slice(0, 7);
    function render() { const entries = read().sort((a, b) => `${b.date}${b.id}`.localeCompare(`${a.date}${a.id}`)); const month = monthPicker.value || new Date().toLocaleDateString("sv-SE").slice(0, 7); const { stamped, manual, target, balance, entries: monthEntries } = monthlyValues(month); renderHomeMonth();
      dialog.querySelector("[data-account-stamped]").textContent = format(stamped); dialog.querySelector("[data-account-manual]").textContent = format(manual, true); dialog.querySelector("[data-account-target]").textContent = format(target); const accountMonth = dialog.querySelector("[data-account-month]"); if (accountMonth) accountMonth.textContent = new Date().toLocaleDateString(locale(), { month: "long", year: "numeric" }); dialog.querySelector("[data-account-balance]").textContent = format(balance, true); dialog.querySelector("[data-account-balance]").classList.toggle("is-negative", balance < 0); const homeCaptured = document.getElementById("privateAccountCaptured"); const homeManual = document.getElementById("privateAccountManual"); const homeBalance = document.getElementById("privateAccountBalance"); if (homeCaptured) homeCaptured.textContent = format(stamped); if (homeManual) homeManual.textContent = `Soll ${format(target)}`; if (homeBalance) { homeBalance.textContent = format(balance, true); homeBalance.classList.toggle("positive", balance >= 0); }
      dialog.querySelector("[data-account-list]").innerHTML = monthEntries.length ? monthEntries.map((entry) => `<article><span><strong>${escapeHtml(entry.note || (entry.source === "stamp" ? "Stempelung" : "Korrektur"))}</strong><small>${new Date(`${entry.date}T12:00:00`).toLocaleDateString(locale(), { day: "2-digit", month: "2-digit", year: "numeric" })} · ${entry.source === "stamp" ? "Automatisch" : "Manuell"}</small></span><b>${entry.source === "stamp" ? format(entry.minutes) : format(entry.adjustment, true)}</b><span class="account-row-actions"><button type="button" data-edit-account="${entry.id}" aria-label="Eintrag korrigieren"><i class="fa-solid fa-pen"></i></button><button type="button" data-delete-account="${entry.id}" aria-label="Eintrag löschen"><i class="fa-regular fa-trash-can"></i></button></span></article>`).join("") : '<p class="private-import-empty">Für diesen Monat sind noch keine Arbeitszeiten vorhanden.</p>';
    }
    form.addEventListener("submit", (event) => { event.preventDefault(); const hours = Number(form.elements.hours.value || 0); const minuteValue = Number(form.elements.minutes.value || 0); const adjustment = Number(form.elements.direction.value) * (hours * 60 + minuteValue); if (!adjustment) return; const entries = read(); const entry = { id: `manual-${Date.now()}`, date: form.elements.date.value, minutes: 0, target: 0, adjustment, note: form.elements.note.value.trim() || "Manuelle Korrektur", source: "manual" }; entries.push(entry); audit("create", entry); write(entries); form.elements.hours.value = "0"; form.elements.minutes.value = "0"; form.elements.note.value = ""; render(); document.dispatchEvent(new CustomEvent("timeflow:private-account-updated")); });
    dialog.querySelector("[data-account-list]").addEventListener("click", (event) => { const remove = event.target.closest("[data-delete-account]"); const edit = event.target.closest("[data-edit-account]"); if (remove) { const entries = read(); const entry = entries.find((item) => item.id === remove.dataset.deleteAccount); if (!entry || !window.confirm("Diesen Arbeitszeiteintrag wirklich löschen?")) return; audit("delete", entry, entry); write(entries.filter((item) => item.id !== entry.id)); render(); document.dispatchEvent(new CustomEvent("timeflow:private-account-updated")); return; } if (edit) { const entries = read(); const entry = entries.find((item) => item.id === edit.dataset.editAccount); if (!entry) return; const current = entry.source === "stamp" ? Number(entry.minutes || 0) : Math.abs(Number(entry.adjustment || 0)); const answer = window.prompt("Korrigierte Dauer in Minuten:", String(current)); if (answer === null || !Number.isFinite(Number(answer)) || Number(answer) < 0) return; const before = { ...entry }; if (entry.source === "stamp") entry.minutes = Number(answer); else entry.adjustment = Math.sign(Number(entry.adjustment || 1)) * Number(answer); entry.note = `${entry.note || "Arbeitszeit"} · korrigiert`; audit("edit", entry, before); write(entries); render(); document.dispatchEvent(new CustomEvent("timeflow:private-account-updated")); } });
    monthPicker.addEventListener("change", render); dialog.querySelector("[data-account-csv]").addEventListener("click", () => downloadCsv(read().filter((entry) => String(entry.date || "").startsWith(monthPicker.value)))); dialog.querySelector("[data-account-pdf]").addEventListener("click", () => printPdf(read().filter((entry) => String(entry.date || "").startsWith(monthPicker.value)))); dialog.querySelector("[data-account-audit]").addEventListener("click", () => { const list = dialog.querySelector("[data-account-audit-list]"); list.hidden = !list.hidden; const events = (readObject(AUDIT_KEY).events || []).slice().reverse(); list.innerHTML = events.length ? events.map((item) => `<article><strong>${item.action === "edit" ? "Korrigiert" : item.action === "delete" ? "Gelöscht" : "Erstellt"}</strong><span>${escapeHtml(item.date)} · ${new Date(item.at).toLocaleString(locale())}</span></article>`).join("") : "<p>Noch keine manuellen Änderungen protokolliert.</p>"; });
    dialog.querySelector("[data-close-private-account]").addEventListener("click", () => platform().dialog.close(dialog)); dialog.addEventListener("click", (event) => { if (event.target === dialog) platform().dialog.close(dialog); });
    document.addEventListener("timeflow:open-private-account", () => { render(); platform().dialog.open(dialog); }); document.addEventListener("timeflow:workday-updated", render); document.addEventListener("timeflow:settings-updated", render); render(); window.setTimeout(render, 0);
  }
  window.TimeFlowPrivateAccount = { refreshHome: renderHomeMonth, captureCompletedWorkday };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", install); else install();
}());
