(function () {
  "use strict";
  const KEY = "timeflow-private-account-v1";
  const platform = () => window.TimeFlowPlatform;
  const read = () => { try { const value = JSON.parse(platform().storage.getItem(KEY) || "[]"); return Array.isArray(value) ? value : []; } catch (_error) { return []; } };
  const write = (entries) => platform().storage.setItem(KEY, JSON.stringify(entries));
  const settings = () => { try { return JSON.parse(platform().storage.getItem("timeflow-settings-v1") || "{}"); } catch (_error) { return {}; } };
  const format = (minutes, signed = false) => { const sign = minutes < 0 ? "−" : signed && minutes > 0 ? "+" : ""; const value = Math.abs(Math.round(minutes)); return `${sign}${Math.floor(value / 60)} h ${value % 60} min`; };
  const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  function captureCompletedWorkday() {
    let workday; try { workday = JSON.parse(platform().storage.getItem("timeflow-workday-v2") || "null"); } catch (_error) { return; }
    if (!workday?.workStart || !workday.workEnd || workday.isWorking) return;
    const entries = read(); const id = `stamp-${workday.workEnd}`; if (entries.some((entry) => entry.id === id)) return;
    const gross = Math.max(0, Math.floor((new Date(workday.workEnd) - new Date(workday.workStart)) / 60000)); const config = settings(); const pause = gross >= Number(config.autoBreakAfterMinutes || 360) ? Number(config.autoBreakMinutes || 30) : 0; const net = Math.max(0, gross - pause); const target = Number(config.dailyTargetMinutes || 480);
    entries.push({ id, date: new Date(workday.workStart).toLocaleDateString("sv-SE"), minutes: net, target, adjustment: 0, note: "Stempelung", source: "stamp" }); write(entries);
  }
  function install() {
    document.body.insertAdjacentHTML("beforeend", `<dialog class="private-account-dialog" id="privateAccountDialog"><header><div><small>PRIVAT · ARBEITSZEITKONTO</small><h2>Mein Arbeitszeitkonto</h2><p>Stempelungen werden automatisch übernommen. Anfangsstände und Korrekturen kannst du manuell ergänzen.</p></div><button type="button" data-close-private-account aria-label="Schließen"><i class="fa-solid fa-xmark"></i></button></header><section class="private-account-summary"><span><small>ERFASSTE ARBEITSZEIT</small><strong data-account-stamped>0 h 0 min</strong></span><span><small>MANUELLE KORREKTUREN</small><strong data-account-manual>0 h 0 min</strong></span><span><small>AKTUELLER SALDO</small><strong data-account-balance>0 h 0 min</strong></span></section><form class="private-account-form"><label>Datum<input name="date" type="date" required></label><label>Art<select name="direction"><option value="1">Guthaben hinzufügen</option><option value="-1">Stunden abziehen</option></select></label><label>Stunden<input name="hours" type="number" min="0" max="9999" value="0" required></label><label>Minuten<input name="minutes" type="number" min="0" max="59" value="0" required></label><label>Notiz<input name="note" type="text" maxlength="80" placeholder="z. B. Anfangsstand oder Korrektur"></label><button type="submit"><i class="fa-solid fa-plus"></i> Im Arbeitszeitkonto speichern</button></form><section class="private-account-list" data-account-list></section></dialog>`);
    const dialog = document.getElementById("privateAccountDialog"); const form = dialog.querySelector("form"); form.elements.date.value = new Date().toLocaleDateString("sv-SE");
    function render() { captureCompletedWorkday(); const entries = read().sort((a, b) => `${b.date}${b.id}`.localeCompare(`${a.date}${a.id}`)); const stamped = entries.filter((entry) => entry.source === "stamp").reduce((sum, entry) => sum + Number(entry.minutes || 0), 0); const manual = entries.filter((entry) => entry.source === "manual").reduce((sum, entry) => sum + Number(entry.adjustment || 0), 0); const stampBalance = entries.filter((entry) => entry.source === "stamp").reduce((sum, entry) => sum + Number(entry.minutes || 0) - Number(entry.target || 0), 0); const balance = stampBalance + manual;
      dialog.querySelector("[data-account-stamped]").textContent = format(stamped); dialog.querySelector("[data-account-manual]").textContent = format(manual, true); dialog.querySelector("[data-account-balance]").textContent = format(balance, true); const homeCaptured = document.getElementById("privateAccountCaptured"); const homeManual = document.getElementById("privateAccountManual"); const homeBalance = document.getElementById("privateAccountBalance"); if (homeCaptured) homeCaptured.textContent = format(stamped); if (homeManual) homeManual.textContent = format(manual, true); if (homeBalance) { homeBalance.textContent = format(balance, true); homeBalance.classList.toggle("positive", balance >= 0); }
      dialog.querySelector("[data-account-list]").innerHTML = entries.length ? entries.map((entry) => `<article><span><strong>${escapeHtml(entry.note || (entry.source === "stamp" ? "Stempelung" : "Korrektur"))}</strong><small>${new Date(`${entry.date}T12:00:00`).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit", year: "numeric" })} · ${entry.source === "stamp" ? "Automatisch" : "Manuell"}</small></span><b>${entry.source === "stamp" ? format(entry.minutes) : format(entry.adjustment, true)}</b>${entry.source === "manual" ? `<button type="button" data-delete-account="${entry.id}" aria-label="Eintrag löschen"><i class="fa-regular fa-trash-can"></i></button>` : "<i></i>"}</article>`).join("") : '<p class="private-import-empty">Noch keine Stempelungen oder manuellen Kontowerte vorhanden.</p>';
    }
    form.addEventListener("submit", (event) => { event.preventDefault(); const hours = Number(form.elements.hours.value || 0); const minuteValue = Number(form.elements.minutes.value || 0); const adjustment = Number(form.elements.direction.value) * (hours * 60 + minuteValue); if (!adjustment) return; const entries = read(); entries.push({ id: `manual-${Date.now()}`, date: form.elements.date.value, minutes: 0, target: 0, adjustment, note: form.elements.note.value.trim() || "Manuelle Korrektur", source: "manual" }); write(entries); form.elements.hours.value = "0"; form.elements.minutes.value = "0"; form.elements.note.value = ""; render(); document.dispatchEvent(new CustomEvent("timeflow:private-account-updated")); });
    dialog.querySelector("[data-account-list]").addEventListener("click", (event) => { const button = event.target.closest("[data-delete-account]"); if (!button) return; write(read().filter((entry) => entry.id !== button.dataset.deleteAccount)); render(); });
    dialog.querySelector("[data-close-private-account]").addEventListener("click", () => platform().dialog.close(dialog)); dialog.addEventListener("click", (event) => { if (event.target === dialog) platform().dialog.close(dialog); });
    document.addEventListener("timeflow:open-private-account", () => { render(); platform().dialog.open(dialog); }); document.addEventListener("timeflow:workday-updated", render); render(); window.setTimeout(render, 0);
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", install); else install();
}());
